title: Made Up
email: tillyreid89@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
# baseurl: "/adam-blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Made Up # add your name
author-pic: madeuptitle.jpg
about-author: Made Up is a Lifestyle & Travel Blog aimed at inspiring others to explore and experience new cultures around the globe.

# Contact links
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: tillyreid89 # Add your Github handle
twitter: '@madeupfr' # Add your Twitter handle
facebook: 'madeupfr' # Add your Facebook handle
instagram: 'madeupfr' # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: tillyreid # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
